### ISSUE TITLE
job descriptions

### ISSUE THREAD

**Issue by lonnen** [mozilla/referral-board#1]
We had a user request this morning for job descriptions that are more descriptive of the role. Requirements are useful for keyword grabbing on job boards, but they are guidelines rather than rules. Instead of --

```
BS in Computer Science, information technology, or related field OR equivalent 
academic/work experience. Five [+] of experience in managing operational teams, 
with an SLA-driven environment.
```

More like --

```
Manage Mozilla's operational efforts in support of large scale, open software services 
in our data centers and in the cloud.
```

**Comment by erikrose** [comment]
+1. Telling them not only what they need but specifically what they'd be doing should cut down on people applying for jobs they're not actually interested in as well.

**Comment by rachelberenbaum** [comment]
Thanks Erik & Chris. We are not removing required years of experience, but I did remove other "prereq. requirements" and replaced them with more of what the day to day would look like for role responsibilities. Let me know if you hear any other feedback!
